<?php
/**
 * This file was generated by Laravel Skeletons.
 * (c) 2025 László Kovács. Licensed under the MIT License.
 * Do not remove this header please!
 */
namespace App\Http\Controllers;

use App\Models\Actor;
use App\Http\Requests\ActorRequest;
use Illuminate\Http\Request;

class ActorController extends Controller
{
    /**
     * Display a listing of the resource with pagination.
     */
    public function index()
    {
        // Retrieve paginated results
        $actors = Actor::paginate(config('app.pagination_limit', 20));

        return view('actors.index', compact('actors'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        

        return view('actors.create');
    }

    /**
     * Store a newly created resource in storage using validated request data.
     */
    public function store(ActorRequest $request)
    {
        Actor::create($request->validated());

        return redirect()->route('actors.index')
            ->with('success', __('skeletons.created_successfully', ['model' => 'Actor']));
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $actor = Actor::findOrFail($id);

        return view('actors.show', compact('actor'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $actor = Actor::findOrFail($id);
        return view('actors.edit', compact('actor'));
    }

    /**
     * Update the specified resource in storage using validated request data.
     */
    public function update(ActorRequest $request, string $id)
    {
        $actor = Actor::findOrFail($id);

        $actor->update($request->validated());

        return redirect()->route('actors.index')
            ->with('success', __('skeletons.updated_successfully', ['model' => 'Actor']));
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $actor = Actor::find($id);

        if ($actor) {
            $actor->delete();
        }

        return redirect()->route('actors.index')
            ->with('success', __('skeletons.deleted_successfully', ['model' => 'Actor']));
    }

    /**
     * Search for resources based on provided needle input.
     */
    public function search(Request $request)
    {
        $needle = $request->get('needle');
        $searchColumn = 'name'; 

        try {
            $actors = Actor::orderBy($searchColumn)
                ->where($searchColumn, 'like', "%{$needle}%")
                ->paginate(config('app.pagination_limit', 20));

            return view('actors.index', compact('actors'));

        } catch (\Illuminate\Database\QueryException $e) {
            if (strpos(strtolower($e->getMessage()), 'unknown column') !== false) {
                $errors = \Illuminate\Support\Facades\Validator::make([], [])
                    ->errors();
                $errors->add('search_error', __('skeletons.search_column_missing', ['column' => $searchColumn]));

                return redirect()->back()->withErrors($errors)->withInput();
            }

            // Handle other potential database errors if needed
            throw $e;
        }
    }
}
