<?php
/**
 * This file was generated by Laravel Skeletons.
 * (c) 2025 László Kovács. Licensed under the MIT License.
 * Do not remove this header please!
 */
namespace App\Http\Controllers;

use App\Models\Category;
use App\Http\Requests\CategoryRequest;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource with pagination.
     */
    public function index()
    {
        // Retrieve paginated results
        $categories = Category::paginate(config('app.pagination_limit', 20));

        return view('categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        

        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage using validated request data.
     */
    public function store(CategoryRequest $request)
    {
        Category::create($request->validated());

        return redirect()->route('categories.index')
            ->with('success', __('skeletons.created_successfully', ['model' => 'Category']));
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $category = Category::findOrFail($id);

        return view('categories.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $category = Category::findOrFail($id);
        return view('categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage using validated request data.
     */
    public function update(CategoryRequest $request, string $id)
    {
        $category = Category::findOrFail($id);

        $category->update($request->validated());

        return redirect()->route('categories.index')
            ->with('success', __('skeletons.updated_successfully', ['model' => 'Category']));
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $category = Category::find($id);

        if ($category) {
            $category->delete();
        }

        return redirect()->route('categories.index')
            ->with('success', __('skeletons.deleted_successfully', ['model' => 'Category']));
    }

    /**
     * Search for resources based on provided needle input.
     */
    public function search(Request $request)
    {
        $needle = $request->get('needle');
        $searchColumn = 'name'; 

        try {
            $categories = Category::orderBy($searchColumn)
                ->where($searchColumn, 'like', "%{$needle}%")
                ->paginate(config('app.pagination_limit', 20));

            return view('categories.index', compact('categories'));

        } catch (\Illuminate\Database\QueryException $e) {
            if (strpos(strtolower($e->getMessage()), 'unknown column') !== false) {
                $errors = \Illuminate\Support\Facades\Validator::make([], [])
                    ->errors();
                $errors->add('search_error', __('skeletons.search_column_missing', ['column' => $searchColumn]));

                return redirect()->back()->withErrors($errors)->withInput();
            }

            // Handle other potential database errors if needed
            throw $e;
        }
    }
}
