<?php
/**
 * This file was generated by Laravel Skeletons.
 * (c) 2025 László Kovács. Licensed under the MIT License.
 * Do not remove this header please!
 */
namespace App\Http\Controllers;

use App\Models\Director;
use App\Http\Requests\DirectorRequest;
use Illuminate\Http\Request;

class DirectorController extends Controller
{
    /**
     * Display a listing of the resource with pagination.
     */
    public function index()
    {
        // Retrieve paginated results
        $directors = Director::paginate(config('app.pagination_limit', 20));

        return view('directors.index', compact('directors'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        

        return view('directors.create');
    }

    /**
     * Store a newly created resource in storage using validated request data.
     */
    public function store(DirectorRequest $request)
    {
        Director::create($request->validated());

        return redirect()->route('directors.index')
            ->with('success', __('skeletons.created_successfully', ['model' => 'Director']));
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $director = Director::findOrFail($id);

        return view('directors.show', compact('director'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $director = Director::findOrFail($id);
        return view('directors.edit', compact('director'));
    }

    /**
     * Update the specified resource in storage using validated request data.
     */
    public function update(DirectorRequest $request, string $id)
    {
        $director = Director::findOrFail($id);

        $director->update($request->validated());

        return redirect()->route('directors.index')
            ->with('success', __('skeletons.updated_successfully', ['model' => 'Director']));
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $director = Director::find($id);

        if ($director) {
            $director->delete();
        }

        return redirect()->route('directors.index')
            ->with('success', __('skeletons.deleted_successfully', ['model' => 'Director']));
    }

    /**
     * Search for resources based on provided needle input.
     */
    public function search(Request $request)
    {
        $needle = $request->get('needle');
        $searchColumn = 'name'; 

        try {
            $directors = Director::orderBy($searchColumn)
                ->where($searchColumn, 'like', "%{$needle}%")
                ->paginate(config('app.pagination_limit', 20));

            return view('directors.index', compact('directors'));

        } catch (\Illuminate\Database\QueryException $e) {
            if (strpos(strtolower($e->getMessage()), 'unknown column') !== false) {
                $errors = \Illuminate\Support\Facades\Validator::make([], [])
                    ->errors();
                $errors->add('search_error', __('skeletons.search_column_missing', ['column' => $searchColumn]));

                return redirect()->back()->withErrors($errors)->withInput();
            }

            // Handle other potential database errors if needed
            throw $e;
        }
    }
}
