<?php
/**
 * This file was generated by Laravel Skeletons.
 * (c) 2025 László Kovács. Licensed under the MIT License.
 * Do not remove this header please!
 */
namespace App\Http\Controllers;

use App\Models\Movie;
use App\Http\Requests\MovieRequest;
use App\Models\Category;
use Illuminate\Http\Request;

class MovieController extends Controller
{
    /**
     * Display a listing of the resource with pagination.
     */
    public function index()
    {
        // Retrieve paginated results
        $movies = Movie::paginate(config('app.pagination_limit', 20));

        return view('movies.index', compact('movies'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        
        $categories = Category::all();

        return view('movies.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage using validated request data.
     */
    public function store(MovieRequest $request)
    {
        Movie::create($request->validated());

        return redirect()->route('movies.index')
            ->with('success', __('skeletons.created_successfully', ['model' => 'Movie']));
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $movie = Movie::findOrFail($id);

        return view('movies.show', compact('movie'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $movie = Movie::findOrFail($id);
        $categories = Category::all();
        return view('movies.edit', compact('movie', 'categories'));
    }

    /**
     * Update the specified resource in storage using validated request data.
     */
    public function update(MovieRequest $request, string $id)
    {
        $movie = Movie::findOrFail($id);

        $movie->update($request->validated());

        return redirect()->route('movies.index')
            ->with('success', __('skeletons.updated_successfully', ['model' => 'Movie']));
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $movie = Movie::find($id);

        if ($movie) {
            $movie->delete();
        }

        return redirect()->route('movies.index')
            ->with('success', __('skeletons.deleted_successfully', ['model' => 'Movie']));
    }

    /**
     * Search for resources based on provided needle input.
     */
    public function search(Request $request)
    {
        $needle = $request->get('needle');
        $searchColumn = 'name'; 

        try {
            $movies = Movie::orderBy($searchColumn)
                ->where($searchColumn, 'like', "%{$needle}%")
                ->paginate(config('app.pagination_limit', 20));

            return view('movies.index', compact('movies'));

        } catch (\Illuminate\Database\QueryException $e) {
            if (strpos(strtolower($e->getMessage()), 'unknown column') !== false) {
                $errors = \Illuminate\Support\Facades\Validator::make([], [])
                    ->errors();
                $errors->add('search_error', __('skeletons.search_column_missing', ['column' => $searchColumn]));

                return redirect()->back()->withErrors($errors)->withInput();
            }

            // Handle other potential database errors if needed
            throw $e;
        }
    }
}
