<?php
/**
 * This file was generated by Laravel Skeletons.
 * (c) 2025 László Kovács. Licensed under the MIT License.
 * Do not remove this header please!
 */
namespace App\Http\Controllers;

use App\Models\Studio;
use App\Http\Requests\StudioRequest;
use Illuminate\Http\Request;

class StudioController extends Controller
{
    /**
     * Display a listing of the resource with pagination.
     */
    public function index()
    {
        // Retrieve paginated results
        $studios = Studio::paginate(config('app.pagination_limit', 20));

        return view('studios.index', compact('studios'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        

        return view('studios.create');
    }

    /**
     * Store a newly created resource in storage using validated request data.
     */
    public function store(StudioRequest $request)
    {
        Studio::create($request->validated());

        return redirect()->route('studios.index')
            ->with('success', __('skeletons.created_successfully', ['model' => 'Studio']));
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $studio = Studio::findOrFail($id);

        return view('studios.show', compact('studio'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $studio = Studio::findOrFail($id);
        return view('studios.edit', compact('studio'));
    }

    /**
     * Update the specified resource in storage using validated request data.
     */
    public function update(StudioRequest $request, string $id)
    {
        $studio = Studio::findOrFail($id);

        $studio->update($request->validated());

        return redirect()->route('studios.index')
            ->with('success', __('skeletons.updated_successfully', ['model' => 'Studio']));
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $studio = Studio::find($id);

        if ($studio) {
            $studio->delete();
        }

        return redirect()->route('studios.index')
            ->with('success', __('skeletons.deleted_successfully', ['model' => 'Studio']));
    }

    /**
     * Search for resources based on provided needle input.
     */
    public function search(Request $request)
    {
        $needle = $request->get('needle');
        $searchColumn = 'name'; 

        try {
            $studios = Studio::orderBy($searchColumn)
                ->where($searchColumn, 'like', "%{$needle}%")
                ->paginate(config('app.pagination_limit', 20));

            return view('studios.index', compact('studios'));

        } catch (\Illuminate\Database\QueryException $e) {
            if (strpos(strtolower($e->getMessage()), 'unknown column') !== false) {
                $errors = \Illuminate\Support\Facades\Validator::make([], [])
                    ->errors();
                $errors->add('search_error', __('skeletons.search_column_missing', ['column' => $searchColumn]));

                return redirect()->back()->withErrors($errors)->withInput();
            }

            // Handle other potential database errors if needed
            throw $e;
        }
    }
}
