<?php
/**
 * This file was generated by Laravel Skeletons.
 * (c) 2025 László Kovács. Licensed under the MIT License.
 * Do not remove this header please!
 */
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ActorController;

// Routes for Actor
Route::get('/actors', [ActorController::class, 'index'])->name('actors.index');
Route::post('/actors', [ActorController::class, 'store'])->name('actors.store');
Route::get('/actors/create', [ActorController::class, 'create'])->name('actors.create');
Route::post('/actors/search', [ActorController::class, 'search'])->name('actors.search');

Route::get('/actors/{actor}', [ActorController::class, 'show'])->name('actors.show');
Route::put('/actors/{actor}', [ActorController::class, 'update'])->name('actors.update');
Route::get('/actors/{actor}/edit', [ActorController::class, 'edit'])->name('actors.edit');
Route::delete('/actors/{actor}', [ActorController::class, 'destroy'])->name('actors.destroy');
