<?php
/**
 * This file was generated by Laravel Skeletons.
 * (c) 2025 László Kovács. Licensed under the MIT License.
 * Do not remove this header please!
 */
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DirectorController;

// Routes for Director
Route::get('/directors', [DirectorController::class, 'index'])->name('directors.index');
Route::post('/directors', [DirectorController::class, 'store'])->name('directors.store');
Route::get('/directors/create', [DirectorController::class, 'create'])->name('directors.create');
Route::post('/directors/search', [DirectorController::class, 'search'])->name('directors.search');

Route::get('/directors/{director}', [DirectorController::class, 'show'])->name('directors.show');
Route::put('/directors/{director}', [DirectorController::class, 'update'])->name('directors.update');
Route::get('/directors/{director}/edit', [DirectorController::class, 'edit'])->name('directors.edit');
Route::delete('/directors/{director}', [DirectorController::class, 'destroy'])->name('directors.destroy');
