<?php
/**
 * This file was generated by Laravel Skeletons.
 * (c) 2025 László Kovács. Licensed under the MIT License.
 * Do not remove this header please!
 */
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MovieController;

// Routes for Movie
Route::get('/movies', [MovieController::class, 'index'])->name('movies.index');
Route::post('/movies', [MovieController::class, 'store'])->name('movies.store');
Route::get('/movies/create', [MovieController::class, 'create'])->name('movies.create');
Route::post('/movies/search', [MovieController::class, 'search'])->name('movies.search');

Route::get('/movies/{movie}', [MovieController::class, 'show'])->name('movies.show');
Route::put('/movies/{movie}', [MovieController::class, 'update'])->name('movies.update');
Route::get('/movies/{movie}/edit', [MovieController::class, 'edit'])->name('movies.edit');
Route::delete('/movies/{movie}', [MovieController::class, 'destroy'])->name('movies.destroy');
