<?php
/**
 * This file was generated by Laravel Skeletons.
 * (c) 2025 László Kovács. Licensed under the MIT License.
 * Do not remove this header please!
 */
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StudioController;

// Routes for Studio
Route::get('/studios', [StudioController::class, 'index'])->name('studios.index');
Route::post('/studios', [StudioController::class, 'store'])->name('studios.store');
Route::get('/studios/create', [StudioController::class, 'create'])->name('studios.create');
Route::post('/studios/search', [StudioController::class, 'search'])->name('studios.search');

Route::get('/studios/{studio}', [StudioController::class, 'show'])->name('studios.show');
Route::put('/studios/{studio}', [StudioController::class, 'update'])->name('studios.update');
Route::get('/studios/{studio}/edit', [StudioController::class, 'edit'])->name('studios.edit');
Route::delete('/studios/{studio}', [StudioController::class, 'destroy'])->name('studios.destroy');
