<?php
/**
 * This file was generated by Laravel Skeletons.
 * (c) 2025 László Kovács. Licensed under the MIT License.
 * Do not remove this header please!
 */
namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model as EloquentModel;

class Actor extends EloquentModel
{
    use HasFactory;

    protected $table = 'actors';

    protected $fillable = ['name', 'gender'];

    public $timestamps = false;

}
