<?php
/**
 * This file was generated by Laravel Skeletons.
 * (c) 2025 László Kovács. Licensed under the MIT License.
 * Do not remove this header please!
 */
namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model as EloquentModel;

class Category extends EloquentModel
{
    use HasFactory;

    protected $table = 'categories';

    protected $fillable = ['category'];

    
    public $timestamps = false;


    public function movies()
    {
        return $this->hasMany(Movie::class, 'categories_id', 'id');
    }

    /*protected $fillable = ['category'];*/
}
