<?php
/**
 * This file was generated by Laravel Skeletons.
 * (c) 2025 László Kovács. Licensed under the MIT License.
 * Do not remove this header please!
 */
namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model as EloquentModel;

class Movie extends EloquentModel
{
    use HasFactory;

    protected $table = 'movies';

    protected $fillable = ['name', 'categories_id', 'description', 'pic_path', 'length', 'release_date','director_id'];

    public $timestamps = false;

    public function category()
    {
        return $this->belongsTo(Category::class, 'categories_id', 'id');
    }

    
    public function director()
    {
        return $this->belongsTo(Director::class, 'director_id', 'id');
    }

}
