<?php
/**
 * This file was generated by Laravel Skeletons.
 * (c) 2025 László Kovács. Licensed under the MIT License.
 * Do not remove this header please!
 */
namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class MovieRequest extends FormRequest
{
    public function authorize()
    {
        return true;
    }

    public function rules()
    {
        if ($this->method() === 'PATCH' || $this->method() === 'PUT') {
            return [
                'name' => 'nullable',
                'categories_id' => 'nullable',
                'description' => 'nullable',
                'pic_path' => 'nullable',
                'length' => 'nullable',
                'release_date' => 'nullable',
            ];
        }
        return [
            'name' => 'required|string',
            'categories_id' => 'required',
            'description' => 'required|string',
            'pic_path' => 'required|string',
            'length' => 'required|string',
            'release_date' => 'required|string',
        ];
    }

    public function messages()
    {
        return [
            'name.required' => __('validate_movie.name.required'),
            'categories_id.required' => __('validate_movie.categories_id.required'),
            'description.required' => __('validate_movie.description.required'),
            'pic_path.required' => __('validate_movie.pic_path.required'),
            'length.required' => __('validate_movie.length.required'),
            'release_date.required' => __('validate_movie.release_date.required'),
        ];
    }
}
